s = "Python Programming"
print(s.capitalize())
print(len(s))
print(s.count("P"))
print(s.casefold())
print(s.upper())
print(s.lower())
print(s.center(28,"*"))
print(s.find("P",2))
print(s.index("y"))
print(s.isalnum())
print(s.isalpha())
print(s.replace("P","Y"))
print(s.swapcase())
print(s.endswith("g"))
print(s.startswith("py"))